_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
max_depth:
    value: 5
n_estimators:
    value: 200
